export const clothes = [
  {
    src: "/images/ClothingPortal/NEODETOURNEMENT.svg",
    grid: 5,
    x: -2176,
    y: -2322,
    parallex: 1.5,
    width: 6257,
    height: 2249,
    type: "image",
  },
    {
    src: "/images/ClothingPortal/girders2.svg",
    grid: 5,
    x: -1817,
    y: -1541,
    parallex: 2,
    width: 5253,
    height: 4199,
    type: "image",
  },
  {
    src: "/images/ClothingPortal/Back1.webp",
    grid: 5,
    x: -270,
    y: 636,
    parallex: 2,
    width: 1328,
    height: 885,
    type: "image",
  },
  {
    src: "/images/ClothingPortal/Back2.webp",
    grid: 5,
    x: 326,
    y: 1079,
    parallex: 2.1,
    width: 1915,
    height: 1009,
    type: "image",
  },
  {
    src: "/images/ClothingPortal/Back3.webp",
    grid: 5,
    x: -180,
    y: 623,
    parallex: 2.3,
    width: 2038,
    height: 849,
    type: "image",
  },
  {
    src: "/images/ClothingPortal/Back4.webp",
    grid: 5,
    x: -1127,
    y: -182,
    parallex: 2.8,
    width: 1280,
    height: 1081,
    type: "image",
  },
  {
    src: "/images/ClothingPortal/Back6.webp",
    grid: 5,
    x: -854,
    y: 840,
    parallex: 1.2,
    width: 1052,
    height: 592,
    type: "image",
  },
  {
    src: "/images/ClothingPortal/Back7.webp",
    grid: 5,
    x: 1098,
    y: -417,
    parallex: 1.8,
    width: 1203,
    height: 801,
    type: "image",
  },
  {
    src: "/images/ClothingPortal/Back8.webp",
    grid: 5,
    x: 1414,
    y: 724,
    parallex: 2.4,
    width: 1108,
    height: 739,
    type: "image",
  },
  {
    src: "/images/ClothingPortal/Back9.webp",
    grid: 5,
    x: 1259,
    y: 267,
    parallex: 2.7,
    width: 749,
    height: 498,
    type: "image",
  },
  {
    src: "/images/ClothingPortal/Back10.webp",
    grid: 5,
    x: 4,
    y: -187,
    parallex: 1.2,
    width: 1332,
    height: 852,
    type: "image",
  },
  {
    src: "/images/ClothingPortal/WA.png",
    grid: 5,
    x: -262,
    y: -1030,
    parallex: 2.1,
    width: 310,
    height: 3165,
    type: "image",
  },
  {
    src: "/images/ClothingPortal/Back11.webp",
    grid: 5,
    x: 171,
    y: 558,
    parallex: 1.3,
    width: 555,
    height: 369,
    type: "image",
  },
  {
    src: "/images/ClothingPortal/SM1.webp",
    grid: 5,
    x: 336,
    y: 833,
    parallex: 3,
    width: 439,
    height: 294,
    type: "image",
  },
  {
    src: "/images/ClothingPortal/SM2.webp",
    grid: 5,
    x: 1081,
    y: 0,
    parallex: 3.2,
    width: 429,
    height: 312,
    type: "image",
  },
  ////////////////////////////////////////////////////////////
  {
    src: "/images/ClothingPortal/SM3.webp",
    grid: 5,
    x: 487,
    y: 29,
    parallex: 4.8,
    width: 506,
    height: 339,
    type: "image",
  },
  {
    src: "/images/ClothingPortal/SM4.webp",
    grid: 5,
    x: 268,
    y: 23,
    parallex: 2.9,
    width: 243,
    height: 194,
    type: "image",
  },
  {
    src: "/images/ClothingPortal/LSColoured2.webp",
    grid: 5,
    x: 634,
    y: 262,
    parallex: 3,
    width: 649,
    height: 546,
    type: "product",
    imageCarousel: [
      "/images/LS-Carousel/LSWebFront.webp",
      "/images/LS-Carousel/LSWebBack.webp",
      "/images/LS-Carousel/LSWebBackDetail.webp",
      "/images/LS-Carousel/LSWebArmDetail.webp",
    ],
    url: "/products/Compliance-Long-Sleeve",
    description:
      "At the Arc-GGD Werbeabteilung (Advertising Department) we develop visual strategies to deliver top results to our civil construction clients. Our advertising activities conform to the most stringent quality standards, enshrined in our GGD Process Authorisation Codes, GPAC®.",
    description2:"100% combed ringspun cotton. Heavyweight 205 gsm. Hand screen printed in London, UK.",
      designer: "Ingeborg Harz",
    sku: "WA|23-HB.002-CLS",
    city: "Munich",
    garmentName: "Compliance™ Long-Sleeve",
    garmentDimensions: {
      width: 1670,
      height: 2300,
      type: "image",
    },
    price: {
      eth: 2,
      gbp: 100,
      euro: 150,
    },
  },
  {
    src: "/images/ClothingPortal/SM5.webp",
    grid: 5,
    x: 506,
    y: 167,
    parallex: 5.1,
    width: 246,
    height: 199,
    type: "image",
  },
  {
    src: "/images/ClothingPortal/SM6.webp",
    grid: 5,
    x: 431,
    y: 250,
    parallex: 6.2,
    width: 228,
    height: 166,
    type: "image",
  },
  {
    src: "/images/ClothingPortal/SM7.webp",
    grid: 5,
    x: 574,
    y: 691,
    parallex: 6.3,
    width: 205,
    height: 171,
    type: "image",
  },
  {
    src: "/images/ClothingPortal/SM8.webp",
    grid: 5,
    x: 392,
    y: 456,
    parallex: 3.4,
    width: 261,
    height: 175,
    type: "image",
  },
  {
    src: "/images/ClothingPortal/SM9.webp",
    grid: 5,
    x: 1133,
    y: 649,
    parallex: 5.5,
    width: 426,
    height: 308,
    type: "image",
  },
  {
    src: "/images/ClothingPortal/SM10.webp",
    grid: 5,
    x: 979,
    y: 775,
    parallex: 2.6,
    width: 244,
    height: 183,
    type: "image",
  },
  {
    src: "/images/ClothingPortal/SM11.webp",
    grid: 5,
    x: -88,
    y: 398,
    parallex: 4.7,
    width: 456,
    height: 306,
    type: "image",
  },
  {
    src: "/images/ClothingPortal/SM12.webp",
    grid: 5,
    x: 1105,
    y: 346,
    parallex: 3.8,
    width: 522,
    height: 462,
    type: "image",
  },
  {
    src: "/images/ClothingPortal/SM13.webp",
    grid: 5,
    x: 1098,
    y: 244,
    parallex: 4.9,
    width: 250,
    height: 189,
    type: "image",
  },
  {
    src: "/images/ClothingPortal/SM14.webp",
    grid: 5,
    x: -191,
    y: 67,
    parallex: 5.6,
    width: 447,
    height: 345,
    type: "image",
  },
  {
    src: "/images/ClothingPortal/SM15.webp",
    grid: 5,
    x: 1355,
    y: 208,
    parallex: 6.3,
    width: 435,
    height: 291,
    type: "image",
  },
  {
    src: "/images/ClothingPortal/ComplianceText.webp",
    grid: 5,
    x: 790,
    y: 851,
    parallex: 3.3,
    width: 342,
    height: 68,
    type: "image",
  },
  {
    src: "/images/ClothingPortal/GPAC.svg",
    grid: 5,
    x: 117,
    y: 411,
    parallex: 5.3,
    width: 2435,
    height: 1234,
    type: "image",
  },
  {
    src: "/images/ClothingPortal/COMPLIANT.svg",
    grid: 5,
    x: -1470,
    y: 24,
    parallex: 3.8,
    width: 4142,
    height: 1739,
    type: "image",
  },
];
