export const prints = [
  {
    src: "/images/PrintPortal/NEOLETTRISME.svg",
    grid: 5,
    x: -909,
    y: -1414,
    parallex: 1.8,
    width: 3812,
    height: 964,
    type: "image",
  },
  {
    src: "/images/PrintPortal/ROSES.svg",
    grid: 5,
    x: -2662,
    y: -1063,
    parallex: 1.8,
    width: 6381,
    height: 4021,
    type: "image",
  },
  {
    src: "/images/PrintPortal/bg1.webp",
    grid: 5,
    x: 2226,
    y: 283,
    parallex: 2.2,
    width: 810,
    height: 745,
    type: "image",
  },

  {
    src: "/images/PrintPortal/bg3.webp",
    grid: 5,
    x: -380,
    y: -565,
    parallex: 2.8,
    width: 1974,
    height: 2480,
    type: "image",
  },
  {
    src: "/images/PrintPortal/bg4.webp",
    grid: 5,
    x: 446,
    y: -427,
    parallex: 1.8,
    width: 1974,
    height: 2480,
    type: "image",
  },
  {
    src: "/images/PrintPortal/bg5.webp",
    grid: 5,
    x: -883,
    y: 563,
    parallex: 2,
    width: 2065,
    height: 1587,
    type: "image",
  },
  {
    src: "/images/PrintPortal/fatInk3.svg",
    grid: 5,
    x: -800,
    y: -500,
    parallex: 1.2,
    width: 2680,
    height: 2107,
    type: "image",
  },
  {
    src: "/images/PrintPortal/bg2.webp",
    grid: 5,
    x: -1216,
    y: -794,
    parallex: 1.4,
    width: 1974,
    height: 2480,
    type: "image",
  },
  {
    src: "/images/PrintPortal/bg6.webp",
    grid: 5,
    x: -1464,
    y: -75,
    parallex: 2.2,
    width: 1946,
    height: 1865,
    type: "image",
  },
  {
    src: "/images/PrintPortal/bg7.webp",
    grid: 5,
    x: 314,
    y: -1368,
    parallex: 2.4,
    width: 2668,
    height: 1706,
    type: "image",
  },
  {
    src: "/images/PrintPortal/bg8.webp",
    grid: 5,
    x: -174,
    y: 1091,
    parallex: 2.6,
    width: 1659,
    height: 995,
    type: "image",
  },
  {
    src: "/images/PrintPortal/bg9.webp",
    grid: 5,
    x: 1257,
    y: -653,
    parallex: 2.8,
    width: 2304,
    height: 3049,
    type: "image",
  },

  {
    src: "/images/PrintPortal/bg10.webp",
    grid: 5,
    x: 1503,
    y: 850,
    parallex: 3,
    width: 1208,
    height: 592,
    type: "image",
  },
  {
    src: "/images/PrintPortal/MotifsBackground.svg",
    grid: 5,
    x: -231,
    y: -225,
    parallex: 3.2,
    width: 2759,
    height: 1728,
    type: "image",
  },
  {
    src: "/images/PrintPortal/MotifsBurgundy.svg",
    grid: 5,
    x: -231,
    y: -312,
    parallex: 5.4,
    width: 2756,
    height: 1760,
    type: "image",
  },
  ////////////////////////////////////////////////////////////
  {
    src: "/images/PrintPortal/PrintOB.webp",
    grid: 5,
    x: -5,
    y: 15,
    parallex: 3.2,
    width: 417,
    height: 602,
    type: "product",
    imageCarousel: [
      "/images/PrintPortal/Black-Front.webp",
      "/images/PrintPortal/Black-L.webp",
      "/images/PrintPortal/Black-R.webp",
    ],
    additionalInfo: [
      "We work with an independent bespoke framer, based in London, UK, to hand-build frames to our precise specification. For the current edition we offer the following framing option:",
      "Natural oak 10mm gallery box frame with dark stain, mounted edge to edge with a 16 mm spacer.",
      "Please note framing will add 3 weeks to the delivery time.",
    ],
    stripeLinks: [
      {
        label: "UNFRAMED",
        url: "https://buy.stripe.com/14kcND7ay5TG39m5kk",
        price: 100,
      },
      {
        label: "FRAMED",
        url: "https://buy.stripe.com/28o5lb0Ma5TGh0c7st",
        price: 180,
      },
    ],
    url: "/products/AdvertisingPrint-OB",
    descriptions: [
      "At the Arc-GGD Werbeabteilung (Advertising Department) we develop visual strategies to deliver top results to our civil construction clients. In the following collaboration with our Abteilung für Bildende Kunst (Fine Art Department), we bring you a selection of our most Compliant™ motifs.",
      "Two colour hand-sprayed background with hand-screen printed detail.",
      "Edition of 10. Stamped, Signed, Certified.",
      "",
    ],
    designer: "ingeborg harz",
    sku: "BK|23-LE.089-AP-OB",
    city: "Munich",
    garmentName: "Advertising Print Orange/Blue/Grey",
    additionalInfoTitle: "Framing info",
    additionalInfoDescription: ["some text about framing info"],
  },
  ////////////////////////////////////////////////////////////

  {
    src: "/images/PrintPortal/PrintBP.png",
    grid: 5,
    x: 689,
    y: 407,
    parallex: 3.8,
    width: 417,
    height: 602,
    type: "product",
    imageCarousel: [
      "/images/PrintPortal/Green-Front.webp",
      "/images/PrintPortal/Green-L.webp",
      "/images/PrintPortal/Green-R.webp",
    ],
    url: "/products/AdvertisingPrint-BP",
    descriptions: [
      "At the Arc-GGD Werbeabteilung (Advertising Department) we develop visual strategies to deliver top results to our civil construction clients. In the following collaboration with our Abteilung für Bildende Kunst (Fine Art Department), we bring you a selection of our most Compliant™ motifs.",
      "Two colour hand-sprayed background with hand-screen printed detail.",
      "Edition of 10. Stamped, Signed, Certified.",
    ],
    stripeLinks: [
      {
        label: "UNFRAMED",
        url: "https://buy.stripe.com/14kcND7ay5TG39m5kk",
        price: 100,
      },
      {
        label: "FRAMED",
        url: "https://buy.stripe.com/28o5lb0Ma5TGh0c7st",
        price: 180,
      },
    ],
    designer: "ingeborg harz",
    sku: "BK|23-LE.089-AP-BP",
    city: "Munich",
    garmentName: "Advertising Print Blue/Pink/Green",
    additionalInfoTitle: "Framing info",
    additionalInfoDescription: ["some text about framing info"],
  },
  ////////////////////////////////////////////////////////////
  {
    src: "/images/PrintPortal/PrintVB.webp",
    grid: 5,
    x: 1438,
    y: -128,
    parallex: 3.9,
    width: 417,
    height: 602,
    type: "product",
    imageCarousel: [
      "/images/PrintPortal/Pink-Front.webp",
      "/images/PrintPortal/Pink-L.webp",
      "/images/PrintPortal/Pink-R.webp",
    ],
    url: "/products/AdvertisingPrint-VB",
    descriptions: [
      "At the Arc-GGD Werbeabteilung (Advertising Department) we develop visual strategies to deliver top results to our civil construction clients. In the following collaboration with our Abteilung für Bildende Kunst (Fine Art Department), we bring you a selection of our most Compliant™ motifs.",
      "Two colour hand-sprayed background with hand-screen printed detail.",
      "Edition of 10. Stamped, Signed, Certified.",
    ],
    stripeLinks: [
      {
        label: "UNFRAMED",
        url: "https://buy.stripe.com/14kcND7ay5TG39m5kk",
        price: 100,
      },
      {
        label: "FRAMED",
        url: "https://buy.stripe.com/28o5lb0Ma5TGh0c7st",
        price: 180,
      },
    ],
    designer: "ingeborg harz",
    sku: "BK|23-LE.089-AP-VB",
    city: "Munich",
    garmentName: "Advertising Print Violet/Blue/Pink",
    additionalInfoTitle: "Framing info",
    additionalInfoDescription: ["some text about framing info"],
  },
  ////////////////////////////////////////////////////////////
  {
    src: "/images/PrintPortal/Titles2.webp",
    grid: 5,
    x: 22,
    y: 418,
    parallex: 4,
    width: 1757,
    height: 626,
    type: "image",
  },
  {
    src: "/images/PrintPortal/MotifsGreen.svg",
    grid: 5,
    x: 390,
    y: 161,
    parallex: 4.2,
    width: 1174,
    height: 584,
    type: "image",
  },
  {
    src: "/images/PrintPortal/MotifsBlue.svg",
    grid: 5,
    x: -236,
    y: -49,
    parallex: 4.4,
    width: 1927,
    height: 1112,
    type: "image",
  },
];
