export const products = [
  // {
  //   id: 1,
  //   src: "/images/webp/backg2.webp",
  //   grid: 5,
  //   x: -500,
  //   y: -500,
  //   parallex: 0.5,
  //   width: 3357,
  //   height: 2518,
  // },
  {
    id: 2,
    src: "/images/webp/merz.webp",
    grid: 5,
    x: 700,
    y: 1050,
    parallex: 2,
    width: 397,
    height: 67,
  },
  {
    id: 1,
    src: "/images/webp/verboten.webp",
    grid: 5,
    x: -200,
    y: 300,
    parallex: 1.5,
    width: 921,
    height: 351,
  },
  {
    id: 1,
    src: "/images/webp/tv.webp",
    grid: 5,
    x: 750,
    y: 600,
    parallex: 2.2,
    width: 278,
    height: 55,
  },
  {
    id: 1,
    src: "/images/webp/tz.webp",
    grid: 5,
    x: 800,
    y: 700,
    parallex: 2.5,
    width: 127,
    height: 150,
  },
  {
    id: 1,
    src: "/images/webp/redwhite.webp",
    grid: 5,
    x: 500,
    y: 100,
    parallex: 2.8,
    width: 306,
    height: 98,
  },
  {
    id: 1,
    src: "/images/webp/flake1.webp",
    grid: 5,
    x: 0,
    y: 100,
    parallex: 2,
    width: 196,
    height: 278,
  },
  {
    id: 1,
    src: "/images/webp/reduziert.webp",
    grid: 5,
    x: 1050,
    y: 100,
    parallex: 2.5,
    width: 182,
    height: 100,
  },
  {
    id: 1,
    src: "/images/webp/solar.webp",
    grid: 5,
    x: 900,
    y: 100,
    parallex: 3.3,
    width: 640,
    height: 772,
  },

  {
    id: 1,
    src: "/images/webp/cba.webp",
    grid: 5,
    x: 400,
    y: 950,
    parallex: 2.2,
    width: 161,
    height: 231,
  },
  {
    id: 1,
    src: "/images/webp/cba.webp",
    grid: 5,
    x: 561,
    y: 950,
    parallex: 2.2,
    width: 161,
    height: 231,
  },
  {
    id: 1,
    src: "/images/webp/affitasi2.webp",
    grid: 5,
    x: 1450,
    y: 500,
    parallex: 3,
    width: 308,
    height: 197,
  },
  {
    id: 1,
    src: "/images/webp/flake2.webp",
    grid: 5,
    x: 300,
    y: 500,
    parallex: 3.6,
    width: 259,
    height: 178,
  },
  {
    id: 1,
    src: "/images/webp/plank.webp",
    grid: 5,
    x: -100,
    y: 50,
    parallex: 3.3,
    width: 537,
    height: 440,
  },
  {
    id: 1,
    src: "/images/webp/wax.webp",
    grid: 5,
    x: 300,
    y: 300,
    parallex: 3.5,
    width: 175,
    height: 306,
  },
  {
    id: 1,
    src: "/images/webp/greengraf.webp",
    grid: 5,
    x: -100,
    y: -400,
    parallex: 3.8,
    width: 532,
    height: 638,
  },
  {
    id: 1,
    src: "/images/webp/samstag.webp",
    grid: 5,
    x: 1400,
    y: 890,
    parallex: 2.8,
    width: 97,
    height: 111,
  },
  {
    id: 1,
    src: "/images/webp/affitasi1.webp",
    grid: 5,
    x: -150,
    y: 700,
    parallex: 3,
    width: 285,
    height: 190,
  },
  {
    id: 1,
    src: "/images/webp/montag.webp",
    grid: 5,
    x: -50,
    y: 870,
    parallex: 3.5,
    width: 97,
    height: 111,
  },
  {
    id: 1,
    src: "/images/webp/yellowgraf.webp",
    grid: 5,
    x: -320,
    y: 800,
    parallex: 4,
    width: 948,
    height: 455,
  },

  {
    id: 1,
    src: "/images/webp/purplegraff.webp",
    grid: 5,
    x: 920,
    y: 600,
    parallex: 3.4,
    width: 89,
    height: 489,
  },
  {
    id: 1,
    src: "/images/webp/redgraff.webp",
    grid: 5,
    x: 1120,
    y: 630,
    parallex: 3.6,
    width: 274,
    height: 199,
  },
  {
    id: 1,
    src: "/images/webp/flake3.webp",
    grid: 5,
    x: 940,
    y: 620,
    parallex: 4,
    width: 276,
    height: 221,
  },
  {
    id: 1,
    src: "/images/webp/placeholder.webp",
    imageCarousel: [
      "/images/webp/placeholder.webp",
      "/images/webp/flake3.webp",
      "/images/webp/redgraff.webp",
    ],
    url: "/basic-tshirt",
    description:
      "Recasting eudaimonia as an earthly rather than purely human flourishing. A vision of eudaimonia positioned alongside contemporary new materialisms that gesture towards the crisis of The Anthropocene. A perspective that both anticipates and increasingly participates in the new human era, with a view to ultimate enfranchisement of the interests of non-human actants.",
    designer: "ingeborg harz",
    sku: "LS1298",
    garmentName: "helion tshirt",
    garmentDimensions: {
      width: 1670,
      height: 2300,
    },
    price: {
      eth: 2,
      gbp: 100,
      euro: 150,
    },
    grid: 5,
    x: 500,
    y: 500,
    parallex: 4,
    width: 412,
    height: 550,
  },
  {
    id: 1,
    src: "/images/webp/placeholder-boxers.webp",
    parallex: 4,
    width: 412,
    height: 550,
    grid: 5,
    x: 1800,
    y: 300,
    imageCarousel: [
      "/images/webp/placeholder.webp",
      "/images/webp/flake3.webp",
      "/images/webp/redgraff.webp",
    ],
    url: "/basic-tshirt",
    description:
      "Recasting eudaimonia as an earthly rather than purely human flourishing. A vision of eudaimonia positioned alongside contemporary new materialisms that gesture towards the crisis of The Anthropocene. A perspective that both anticipates and increasingly participates in the new human era, with a view to ultimate enfranchisement of the interests of non-human actants.",
    designer: "ingeborg harz",
    sku: "LS1298",
    garmentName: "helion tshirt",
    garmentDimensions: {
      width: 1670,
      height: 2300,
    },
    price: {
      eth: 2,
      gbp: 100,
      euro: 150,
    },
  },
];
