export const products = [
  {
    src: "/images/webp/PixLogo.svg",
    grid: 5,
    x: -500,
    y: -500,
    parallex: 1.3,
    width: 4000,
    height: 4000,
    type: "image",
  },
  {
    src: "/images/webp/backg2.webp",
    grid: 5,
    x: -500,
    y: -500,
    parallex: 1.3,
    width: 3357,
    height: 2518,
    type: "image",
  },
  {
    src: "/images/webp/building1.png",
    grid: 5,
    x: -500,
    y: 500,
    parallex: 2.2,
    width: 2725,
    height: 1900,
    type: "image",
  },
  {
    src: "/images/webp/Danke.webp",
    grid: 5,
    x: 200,
    y: 300,
    parallex: 2.6,
    width: 270,
    height: 307,
    type: "image",
  },
  {
    src: "/images/webp/euph.webp",
    grid: 5,
    x: -400,
    y: 350,
    parallex: 3,
    width: 375,
    height: 444,
    type: "image",
  },
  {
    id: 2,
    src: "/images/webp/merz.webp",
    grid: 5,
    x: 1300,
    y: 900,
    parallex: 2,
    width: 494,
    height: 83,
    type: "image",
  },
  {
    src: "/images/webp/GGD security.webp",
    grid: 5,
    x: 861,
    y: 700,
    parallex: 2.2,
    width: 329,
    height: 142,
    type: "image",
  },
  {
    src: "/images/webp/sia.webp",
    grid: 5,
    x: 2291,
    y: 900,
    parallex: 3,
    width: 257,
    height: 201,
    type: "image",
  },
  {
    src: "/images/webp/verboten.webp",
    grid: 5,
    x: 200,
    y: 300,
    parallex: 0.9,
    width: 1867,
    height: 712,
    type: "image",
  },
  {
    src: "/images/webp/tv.webp",
    grid: 5,
    x: 750,
    y: 600,
    parallex: 2.2,
    width: 278,
    height: 55,
    type: "image",
  },
  {
    src: "/images/webp/Crane1.webp",
    grid: 5,
    x: 1600,
    y: -100,
    parallex: 2.2,
    width: 500,
    height: 1294,
    type: "image",
  },

  {
    src: "/images/webp/tz.webp",
    grid: 5,
    x: 800,
    y: 700,
    parallex: 2.5,
    width: 127,
    height: 150,
    type: "image",
  },
  {
    src: "/images/webp/redwhite.webp",
    grid: 5,
    x: 500,
    y: 20,
    parallex: 3.4,
    width: 306,
    height: 98,
    type: "image",
  },
  {
    src: "/images/webp/flake1.webp",
    grid: 5,
    x: 0,
    y: 100,
    parallex: 2.5,
    width: 244,
    height: 346,
    type: "image",
  },
  {
    src: "/images/webp/reduziert.webp",
    grid: 5,
    x: 1050,
    y: 100,
    parallex: 3.8,
    width: 365,
    height: 200,
    type: "image",
  },
  //////////////////////////////////////////////////////
  {
    src: "/images/ClothingPortal/SM8.webp",
    grid: 5,
    x: 1350,
    y: 100,
    parallex: 3.8,
    width: 261,
    height: 175,
    type: "image",
  },
  {
    src: "/images/ClothingPortal/SM1.webp",
    grid: 5,
    x: 1190,
    y: 1000,
    parallex: 3.8,
    width: 439,
    height: 295,
    type: "image",
  },
  {
    src: "/images/ClothingPortal/SM6.webp",
    grid: 5,
    x: 50,
    y: 100,
    parallex: 3.8,
    width: 229,
    height: 167,
    type: "image",
  },

  //////////////////////////////////////////////////////
  {
    src: "/images/webp/ggd pix1.webp",
    grid: 5,
    x: 1100,
    y: -100,
    parallex: 3.3,
    width: 350,
    height: 344,
    type: "image",
  },
  {
    src: "/images/webp/sudballons.webp",
    grid: 5,
    x: 500,
    y: 500,
    parallex: 4,
    width: 372,
    height: 265,
    type: "image",
  },
  {
    src: "/images/webp/solar.webp",
    grid: 5,
    x: 1300,
    y: 0,
    parallex: 4.3,
    width: 794,
    height: 479,
    type: "image",
  },
  {
    src: "/images/webp/cba.webp",
    grid: 5,
    x: 400,
    y: 950,
    parallex: 2.2,
    width: 322,
    height: 462,
    type: "image",
  },
  {
    src: "/images/webp/ggd pix 2.webp",
    grid: 5,
    x: 600,
    y: 850,
    parallex: 3,
    width: 346,
    height: 346,
    type: "image",
  },
  {
    src: "/images/webp/sicherheit.webp",
    grid: 5,
    x: 150,
    y: 950,
    parallex: 3.4,
    width: 591,
    height: 59,
    type: "image",
  },
  {
    src: "/images/webp/affitasi2.webp",
    grid: 5,
    x: 1950,
    y: 500,
    parallex: 3,
    width: 308,
    height: 197,
    type: "image",
  },
  {
    src: "/images/webp/flake2.webp",
    grid: 5,
    x: 500,
    y: 600,
    parallex: 3.6,
    width: 322,
    height: 221,
    type: "image",
  },
  {
    src: "/images/webp/plank.webp",
    grid: 5,
    x: 400,
    y: 50,
    parallex: 4.3,
    width: 666,
    height: 546,
    type: "image",
  },
  {
    src: "/images/webp/wax.webp",
    grid: 5,
    x: 900,
    y: 300,
    parallex: 4,
    width: 351,
    height: 613,
    type: "image",
  },
  {
    src: "/images/webp/greengraf.webp",
    grid: 5,
    x: -100,
    y: 100,
    parallex: 4.8,
    width: 660,
    height: 792,
    type: "image",
  },
  {
    src: "/images/webp/samstag.webp",
    grid: 5,
    x: 2050,
    y: 890,
    parallex: 2.8,
    width: 194,
    height: 221,
    type: "image",
  },
  {
    src: "/images/webp/affitasi1.webp",
    grid: 5,
    x: 50,
    y: 700,
    parallex: 3,
    width: 353,
    height: 236,
    type: "image",
  },
  {
    src: "/images/webp/montag.webp",
    grid: 5,
    x: -50,
    y: 870,
    parallex: 3.5,
    width: 126,
    height: 144,
    type: "image",
  },
  {
    src: "/images/webp/yellowgraf.webp",
    grid: 5,
    x: -470,
    y: 850,
    parallex: 4.5,
    width: 605,
    height: 564,
    type: "image",
  },
  {
    src: "/images/webp/purplegraff.webp",
    grid: 5,
    x: 1320,
    y: 900,
    parallex: 4.4,
    width: 89,
    height: 489,
    type: "image",
  },
  {
    src: "/images/webp/redgraff.webp",
    grid: 5,
    x: 1120,
    y: 630,
    parallex: 3.6,
    width: 340,
    height: 246,
    type: "image",
  },
  {
    src: "/images/webp/flake3.webp",
    grid: 5,
    x: 1240,
    y: 720,
    parallex: 4,
    width: 467,
    height: 373,
    type: "image",
  },
  {
    src: "/images/webp/GreenBlur.svg",
    grid: 5,
    x: -320,
    y: 100,
    parallex: 4,
    width: 583,
    height: 801,
    type: "image",
  },
  {
    src: "/images/webp/GreenBlur.svg",
    grid: 5,
    x: 1560,
    y: 450,
    parallex: 4,
    width: 563,
    height: 561,
    type: "image",
  },
  ///////////////////////////////////////////////////////////////////////////////////////////////////////////
  {
    src: "/images/webp/ClothingPortalImageDS.webp",
    grid: 5,
    x: -300,
    y: 200,
    parallex: 4.5,
    width: 452,
    height: 600,
    type: "product",
    imageCarousel: [
      "/images/product-details/stone-bg.webp",
      "/images/product-details/stone-bg.webp",
      "/images/product-details/stone-bg.webp",
      "/images/product-details/stone-bg.webp",
      "/images/product-details/stone-bg.webp",
      "/images/product-details/stone-bg.webp",
      "/images/product-details/stone-bg.webp",
      "/images/product-details/stone-bg.webp",
    ],
    stripeLinks: [
      {
        small: "https://www.stripe.com/gb",
        medium: "https://www.stripe.com/gb",
        large: "https://www.stripe.com/gb",
        extraLarge: "https://www.stripe.com/gb",
      },
    ],
    url: "/clothing",
    description: "dwdwdwdt.",
    designer: "gordon Cole",
    sku: "Another",
    city: "London",
    garmentName: "helion tshirt",
    garmentDimensions: {
      width: 1670,
      height: 2300,
      type: "image",
    },
    price: {
      eth: 2,
      gbp: 500,
      euro: 150,
    },
  },
  //////////////////////////////////////////////////////////////////////////////////////////////////////
  {
    src: "/images/webp/ArtPortalImageDS.webp",
    grid: 5,
    x: 1600,
    y: 500,
    parallex: 4,
    width: 531,
    height: 543,
    type: "product",
    imageCarousel: [],
    url: "/prints",
    description: "",
    designer: "",
    sku: "",
    city: "",
    garmentName: "",
    garmentDimensions: {
      width: 1670,
      height: 2300,
      type: "image",
    },
    price: {
      eth: 2,
      gbp: 100,
      euro: 150,
    },
  },
  ///////////////////////////////////////////////////////////////////////////////////////////////////////////
];
